services:
  frontend:
    build:
      context: ../../
      dockerfile: docker/dockerfiles/Dockerfile.local
      target: frontend-dev
    container_name: license_frontend_dev
    ports:
      - "3000:3000"
    volumes:
      - ../../frontend:/app
      - node_modules:/app/node_modules
      - next_cache:/app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true

  backend:
    build:
      context: ../../
      dockerfile: docker/dockerfiles/Dockerfile.local
      target: backend-run
    container_name: license_backend_dev
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/licenses
      - JWT_SECRET=<JWT SECRET>
      - RSA_PRIVATE_KEY_PATH=rsa_private.pem
      - RSA_PUBLIC_KEY_PATH=rsa_public.pem

    depends_on:
      - db
      - migrate

  db:
    image: postgres:15
    container_name: license_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: licenses
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  migrate:
    image: migrate/migrate
    container_name: license_migrate
    depends_on:
      - db
    volumes:
      - ../../backend/migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:postgres@db:5432/licenses?sslmode=disable",
      "up"
    ]


volumes:
  pgdata:
  node_modules:
  next_cache:
